package render

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"html"
	"strings"

	"netmap/internal/model"
)

const vendoredMermaidVersion = "11.4.1"

//go:embed assets/mermaid.min.js
var mermaidRuntimeJS string

//go:embed assets/mermaid.LICENSE
var mermaidLicense string

func renderHTML(report model.Report) ([]byte, error) {
	graph := string(renderMermaid(report))
	graphJSON, err := json.Marshal(graph)
	if err != nil {
		return nil, fmt.Errorf("marshal mermaid graph for html: %w", err)
	}

	title := html.EscapeString(htmlPageTitle(report))

	var b strings.Builder
	b.Grow(len(mermaidRuntimeJS) + len(graph) + len(mermaidLicense) + 4096)
	b.WriteString("<!DOCTYPE html>\n")
	b.WriteString("<!--\n")
	b.WriteString("Generated by netmap.\n")
	b.WriteString("This file embeds Mermaid.js v")
	b.WriteString(vendoredMermaidVersion)
	b.WriteString(" under the MIT License.\n\n")
	b.WriteString(strings.TrimSpace(mermaidLicense))
	b.WriteString("\n-->\n")
	b.WriteString("<html lang=\"en\">\n<head>\n")
	b.WriteString("  <meta charset=\"utf-8\">\n")
	b.WriteString("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n")
	b.WriteString("  <title>")
	b.WriteString(title)
	b.WriteString("</title>\n")
	b.WriteString("  <style>\n")
	b.WriteString("    :root { color-scheme: light; }\n")
	b.WriteString("    body { margin: 0; font-family: \"Segoe UI\", Helvetica, Arial, sans-serif; background: #f4f7fb; color: #16202a; }\n")
	b.WriteString("    main { max-width: 1600px; margin: 0 auto; padding: 24px; }\n")
	b.WriteString("    h1 { margin: 0 0 8px; font-size: 1.5rem; }\n")
	b.WriteString("    p { margin: 0 0 16px; color: #425466; }\n")
	b.WriteString("    .panel { background: #fff; border: 1px solid #d7e0ea; border-radius: 12px; box-shadow: 0 10px 30px rgba(15, 23, 42, 0.08); padding: 20px; overflow-x: auto; }\n")
	b.WriteString("    #diagram { min-width: max-content; }\n")
	b.WriteString("    #status { display: none; margin: 0 0 16px; padding: 12px 14px; border-radius: 10px; background: #fff3cd; color: #7a5a00; border: 1px solid #ffe08a; }\n")
	b.WriteString("    details { margin-top: 16px; }\n")
	b.WriteString("    summary { cursor: pointer; font-weight: 600; }\n")
	b.WriteString("    #source { white-space: pre-wrap; word-break: break-word; background: #0f172a; color: #e2e8f0; border-radius: 10px; padding: 16px; overflow-x: auto; }\n")
	b.WriteString("  </style>\n")
	b.WriteString("</head>\n<body>\n")
	b.WriteString("  <main>\n")
	b.WriteString("    <h1>")
	b.WriteString(title)
	b.WriteString("</h1>\n")
	b.WriteString("    <p>Self-contained Mermaid output generated by netmap. Open this file directly in a browser; no CDN or external viewer is required.</p>\n")
	b.WriteString("    <div id=\"status\"></div>\n")
	b.WriteString("    <section class=\"panel\">\n")
	b.WriteString("      <pre id=\"diagram\" class=\"mermaid\"></pre>\n")
	b.WriteString("    </section>\n")
	b.WriteString("    <details>\n")
	b.WriteString("      <summary>Mermaid source</summary>\n")
	b.WriteString("      <pre id=\"source\"></pre>\n")
	b.WriteString("    </details>\n")
	b.WriteString("  </main>\n")
	b.WriteString("  <script>\n")
	b.WriteString(mermaidRuntimeJS)
	b.WriteString("\n  </script>\n")
	b.WriteString("  <script>\n")
	b.WriteString("    const graph = ")
	b.Write(graphJSON)
	b.WriteString(";\n")
	b.WriteString("    const diagram = document.getElementById('diagram');\n")
	b.WriteString("    const source = document.getElementById('source');\n")
	b.WriteString("    const status = document.getElementById('status');\n")
	b.WriteString("    diagram.textContent = graph;\n")
	b.WriteString("    source.textContent = graph;\n")
	b.WriteString("    if (!window.mermaid) {\n")
	b.WriteString("      status.style.display = 'block';\n")
	b.WriteString("      status.textContent = 'Mermaid runtime failed to load.';\n")
	b.WriteString("    } else {\n")
	b.WriteString("      mermaid.initialize({ startOnLoad: false, securityLevel: 'loose', flowchart: { htmlLabels: true, useMaxWidth: false } });\n")
	b.WriteString("      Promise.resolve(mermaid.run({ nodes: [diagram] })).catch((error) => {\n")
	b.WriteString("        status.style.display = 'block';\n")
	b.WriteString("        status.textContent = 'Failed to render Mermaid diagram: ' + (error && error.message ? error.message : String(error));\n")
	b.WriteString("      });\n")
	b.WriteString("    }\n")
	b.WriteString("  </script>\n")
	b.WriteString("</body>\n</html>\n")
	return []byte(b.String()), nil
}

func htmlPageTitle(report model.Report) string {
	source := report.SourceProject
	if strings.TrimSpace(source) == "" {
		source = report.Selectors.Org + " all"
	}
	target := report.DestinationProject
	if strings.TrimSpace(target) == "" {
		target = report.Selectors.Org + " all"
	}
	return fmt.Sprintf("netmap %s: %s to %s", report.Type, source, target)
}
