package render

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"html"
	"net/url"
	"strings"

	"netmap/internal/model"
)

const vendoredMermaidVersion = "11.4.1"

//go:embed assets/mermaid.min.js
var mermaidRuntimeJS string

//go:embed assets/mermaid.LICENSE
var mermaidLicense string

func renderHTML(report model.Report) ([]byte, error) {
	graph := string(renderMermaid(report))
	graphJSON, err := json.Marshal(graph)
	if err != nil {
		return nil, fmt.Errorf("marshal mermaid graph for html: %w", err)
	}

	summary := htmlSelectorSummary(report)
	title := html.EscapeString(htmlPageTitle(report))
	faviconURL := htmlFaviconDataURL()

	var b strings.Builder
	b.Grow(len(mermaidRuntimeJS) + len(graph) + len(mermaidLicense) + 4096)
	b.WriteString("<!DOCTYPE html>\n")
	b.WriteString("<!--\n")
	b.WriteString("Generated by netmap.\n")
	b.WriteString("This file embeds Mermaid.js v")
	b.WriteString(vendoredMermaidVersion)
	b.WriteString(" under the MIT License.\n\n")
	b.WriteString(strings.TrimSpace(mermaidLicense))
	b.WriteString("\n-->\n")
	b.WriteString("<html lang=\"en\">\n<head>\n")
	b.WriteString("  <meta charset=\"utf-8\">\n")
	b.WriteString("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n")
	b.WriteString("  <link rel=\"icon\" type=\"image/svg+xml\" href=\"")
	b.WriteString(html.EscapeString(faviconURL))
	b.WriteString("\">\n")
	b.WriteString("  <title>")
	b.WriteString(title)
	b.WriteString("</title>\n")
	b.WriteString("  <style>\n")
	b.WriteString("    :root { color-scheme: light; }\n")
	b.WriteString("    body { margin: 0; font-family: \"Segoe UI\", Helvetica, Arial, sans-serif; background: #f4f7fb; color: #16202a; }\n")
	b.WriteString("    main { max-width: 1600px; margin: 0 auto; padding: 24px; }\n")
	b.WriteString("    h1 { margin: 0 0 8px; font-size: 1.5rem; }\n")
	b.WriteString("    p { margin: 0 0 16px; color: #425466; }\n")
	b.WriteString("    .summary-table { display: grid; gap: 10px 16px; margin: 0 0 16px; padding: 16px 18px; background: #fff; border: 1px solid #d7e0ea; border-radius: 12px; box-shadow: 0 10px 30px rgba(15, 23, 42, 0.08); }\n")
	b.WriteString("    .summary-label { font-size: 0.75rem; font-weight: 700; letter-spacing: 0.04em; text-transform: uppercase; color: #60758a; }\n")
	b.WriteString("    .summary-value { font-size: 1rem; font-weight: 600; color: #16202a; }\n")
	b.WriteString("    .panel { background: #fff; border: 1px solid #d7e0ea; border-radius: 12px; box-shadow: 0 10px 30px rgba(15, 23, 42, 0.08); padding: 20px; overflow-x: auto; }\n")
	b.WriteString("    #diagram { min-width: max-content; }\n")
	b.WriteString("    #status { display: none; margin: 0 0 16px; padding: 12px 14px; border-radius: 10px; background: #fff3cd; color: #7a5a00; border: 1px solid #ffe08a; }\n")
	b.WriteString("    details { margin-top: 16px; }\n")
	b.WriteString("    summary { cursor: pointer; font-weight: 600; }\n")
	b.WriteString("    #source { white-space: pre-wrap; word-break: break-word; background: #0f172a; color: #e2e8f0; border-radius: 10px; padding: 16px; overflow-x: auto; }\n")
	b.WriteString("  </style>\n")
	b.WriteString("</head>\n<body>\n")
	b.WriteString("  <main>\n")
	b.WriteString("    <h1>")
	b.WriteString(title)
	b.WriteString("</h1>\n")
	b.WriteString("    <div class=\"summary-table\" style=\"grid-template-columns: repeat(")
	b.WriteString(fmt.Sprintf("%d", len(summary.Fields)))
	b.WriteString(", minmax(120px, 1fr));\">\n")
	for _, field := range summary.Fields {
		b.WriteString("      <div class=\"summary-label\">")
		b.WriteString(html.EscapeString(field.Label))
		b.WriteString("</div>\n")
	}
	for _, field := range summary.Fields {
		b.WriteString("      <div class=\"summary-value\">")
		b.WriteString(html.EscapeString(field.Value))
		b.WriteString("</div>\n")
	}
	b.WriteString("    </div>\n")
	b.WriteString("    <p>Self-contained Mermaid output generated by netmap. Open this file directly in a browser; no CDN or external viewer is required.</p>\n")
	b.WriteString("    <div id=\"status\"></div>\n")
	b.WriteString("    <section class=\"panel\">\n")
	b.WriteString("      <pre id=\"diagram\" class=\"mermaid\"></pre>\n")
	b.WriteString("    </section>\n")
	b.WriteString("    <details>\n")
	b.WriteString("      <summary>Mermaid source</summary>\n")
	b.WriteString("      <pre id=\"source\"></pre>\n")
	b.WriteString("    </details>\n")
	b.WriteString("  </main>\n")
	b.WriteString("  <script>\n")
	b.WriteString(mermaidRuntimeJS)
	b.WriteString("\n  </script>\n")
	b.WriteString("  <script>\n")
	b.WriteString("    const graph = ")
	b.Write(graphJSON)
	b.WriteString(";\n")
	b.WriteString("    const diagram = document.getElementById('diagram');\n")
	b.WriteString("    const source = document.getElementById('source');\n")
	b.WriteString("    const status = document.getElementById('status');\n")
	b.WriteString("    diagram.textContent = graph;\n")
	b.WriteString("    source.textContent = graph;\n")
	b.WriteString("    if (!window.mermaid) {\n")
	b.WriteString("      status.style.display = 'block';\n")
	b.WriteString("      status.textContent = 'Mermaid runtime failed to load.';\n")
	b.WriteString("    } else {\n")
	b.WriteString("      mermaid.initialize({ startOnLoad: false, securityLevel: 'loose', maxTextSize: 6000000, maxEdges: 4000, flowchart: { htmlLabels: true, useMaxWidth: false } });\n")
	b.WriteString("      Promise.resolve(mermaid.run({ nodes: [diagram] })).catch((error) => {\n")
	b.WriteString("        status.style.display = 'block';\n")
	b.WriteString("        status.textContent = 'Failed to render Mermaid diagram: ' + (error && error.message ? error.message : String(error));\n")
	b.WriteString("      });\n")
	b.WriteString("    }\n")
	b.WriteString("  </script>\n")
	b.WriteString("</body>\n</html>\n")
	return []byte(b.String()), nil
}

type htmlSummaryValues struct {
	Type        string
	Org         string
	Environment string
	Workload    string
	Fields      []htmlSummaryField
}

type htmlSummaryField struct {
	Label string
	Value string
}

func htmlSelectorSummary(report model.Report) htmlSummaryValues {
	typeValue := properCaseValue(valueOrUnknown(report.Type))
	orgValue := strings.ToUpper(valueOrUnknown(report.Selectors.Org))
	workloadValue := properCaseValue(selectorValueOrAll(report.Selectors.Workload))
	environmentValue := uppercaseSelectorValue(selectorValueOrAll(report.Selectors.Environment))

	fields := []htmlSummaryField{
		{Label: "Type", Value: typeValue},
		{Label: "Org", Value: orgValue},
	}
	if workloadValue == "All" && environmentValue == "All" {
		fields = append(fields, htmlSummaryField{Label: "Workload / Environment", Value: "All"})
	} else {
		fields = append(fields,
			htmlSummaryField{Label: "Environment", Value: environmentValue},
			htmlSummaryField{Label: "Workload", Value: workloadValue},
		)
	}

	return htmlSummaryValues{
		Type:        typeValue,
		Org:         orgValue,
		Environment: environmentValue,
		Workload:    workloadValue,
		Fields:      fields,
	}
}

func htmlPageTitle(report model.Report) string {
	summary := htmlSelectorSummary(report)
	if summary.Workload == "All" && summary.Environment == "All" {
		return fmt.Sprintf("NetMap | %s+%s+All | HTML-Generated Mermaid Report", summary.Type, summary.Org)
	}
	return fmt.Sprintf("NetMap | %s+%s+%s+%s | HTML-Generated Mermaid Report", summary.Type, summary.Org, summary.Workload, summary.Environment)
}

func selectorValueOrAll(value string) string {
	if strings.TrimSpace(value) == "" {
		return "All"
	}
	return value
}

func properCaseValue(value string) string {
	value = strings.TrimSpace(value)
	if value == "" {
		return ""
	}
	if strings.EqualFold(value, "all") {
		return "All"
	}
	segments := strings.Split(value, "-")
	for idx, segment := range segments {
		if segment == "" {
			continue
		}
		segments[idx] = strings.ToUpper(segment[:1]) + strings.ToLower(segment[1:])
	}
	return strings.Join(segments, "-")
}

func uppercaseSelectorValue(value string) string {
	if strings.EqualFold(strings.TrimSpace(value), "all") {
		return "All"
	}
	return strings.ToUpper(strings.TrimSpace(value))
}

func htmlFaviconDataURL() string {
	svg := `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="12" fill="#16202a"/><text x="32" y="18" text-anchor="middle" font-family="monospace" font-size="11" fill="#f8fafc">o-o</text><text x="32" y="33" text-anchor="middle" font-family="monospace" font-size="11" fill="#93c5fd">|x|</text><text x="32" y="48" text-anchor="middle" font-family="monospace" font-size="11" fill="#f8fafc">o-o</text></svg>`
	return "data:image/svg+xml," + url.QueryEscape(svg)
}
